[general]
basedir = C:\\Users\\Lab\\CLionProjects\\automatic_aifes-main\\assets\\dataset\\cifar10\\16x16
training = 1
pruning = 90.0
pruning_aware_training = 1
quantization = Q31
;quantization = Q7
;load = mnist_load.csv
;save = mnist_save.csv

[network]
epochs = 10
batch_size = 32
loss = crossentropy

[dataset]
input = 1,3,16,16

[layer0]
type = conv2d
filters = 16
kernel_size = 3,3
stride = 1,1
dilation = 1,1
padding = 1,1

[layer1]
type = batch_normalization
momentum = 0.9
eps = 1e-6

[layer2]
type = activation
activation = relu

[layer3]
type = conv2d
filters = 32
kernel_size = 3,3
stride = 1,1
dilation = 1,1
padding = 1,1

[layer4]
type = batch_normalization
momentum = 0.9
eps = 1e-6

[layer5]
type = activation
activation = relu

[layer6]
type = maxpool2d
pool_size = 2,2
stride = 2,2
padding = 0,0

[layer7]
type = flatten

[layer8]
type = dense
neurons = 10
activation = softmax