[general]
basedir = C:\\Users\\play_\\Documents\\GitHub\\automatic_aifes\\assets\\dataset\\leo
training = 1
;load = save.csv
;save = save.csv
pruning = 60
pruning_step = 2

[network]
epochs = 10
batch_size = 32
loss = crossentropy

[dataset]
input = 1,77

[layer0]
type = dense
activation = relu
neurons = 16

[layer1]
type = output
activation = softmax
neurons = 8