[general]
basedir = C:\\Users\\play_\\Documents\\GitHub\\automatic_aifes\\assets\\dataset\\leo
;load = mnist_load.csv
save = mnist_save.csv

[network]
epochs = 10
batch_size = 64
loss = crossentropy

[dataset]
input = 1,1,28,28

[layer0]
type = conv2d
filters = 12
kernel_size = 3,3
stride = 1,1
dilation = 1,1
padding = 1,1

[layer1]
type = batch_normalization
momentum = 0.9
eps = 1e-6

[layer2]
activation = relu

[layer3]
type = maxpool2d
pool_size = 2,2
stride = 2,2
padding = 1,1

[layer4]
type = flatten

[layer5]
type = dense
activation = softmax
neurons = 10