[general]
basedir = C:\\Users\\User\\Documents\\GitHub\\automatic_aifes\\assets\\dataset\\mnist\\14x14
;training = 1
;pruning_aware_training = 1
;pruning = 10.0
;quantization = Q31
;quantization = Q7
load = mnist_save.csv
;save = mnist_save.csv

[network]
epochs = 1
batch_size = 32
loss = crossentropy

[dataset]
input = 1,1,14,14

[layer0]
type = conv2d
filters = 16
kernel_size = 3,3
stride = 1,1
dilation = 1,1
padding = 1,1

[layer1]
type = batch_normalization
momentum = 0.9
eps = 1e-6

[layer2]
type = activation
activation = relu

[layer3]
type = maxpool2d
pool_size = 2,2
stride = 2,2
padding = 0,0

[layer4]
type = flatten

[layer5]
type = dense
neurons = 10
activation = softmax